#	
# Notas
#===========================================================================
# Created with: 	Virtual Studio Code
# Created on:   	26/01/2019 21:31
# Created by:   	Chaos4455 	
#===========================================================================
# DESCRIÇÃO
#	Este arquivo possui um template básico de deploy de um stack alpine
#
version: '3'
services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M