version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: mysql
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    networks:
      - mysql
networks:
  mysql: